### ISSUE TITLE
javascript clientside validation use wrong class.

### ISSUE THREAD

**Issue by farmani** [MacGyer/yii2-materializecss#4] opened 2016-03-28 14:25 UTC
js validation use 'valid' for errorCssClass too I don't know the reason but I think there is a bug that use successCssClass for all situations

**Comment by MacGyer** [comment] 2016-07-26 20:46
Hello farmani,

sorry for not getting back to you earlier. But could you please provide me with more information?
What exactly are you doing.

What is your form field config?
Can you post some demo link or source code you think is behaving wrong? (Yii2 rendered HTML, etc.)?

Currently I am not able to reproduce the error you describe, so it would be highly appreciated to get more information about the case.

Thanks

**Comment by farmani-eigital** [comment] 2016-07-27 04:11
Hi @MacGyer 
Sorry but I cannot remember it :( you can close this and wait if any body else complain about it.

**Comment by MacGyer** [comment] 2016-07-27 06:28
Hello @farmani-eigital,

thx for getting back. I will close this for now, but further investigate the behavior of client side validation. If anything occurs, I will reopen the issue and deploy the fix.

CHeers

**Closed** 2016-07-27 06:29 UTC
Labels: bug
