### ISSUE TITLE
Installed files don't match src

### ISSUE THREAD

**Issue by wardjk** [MacGyer/yii2-materializecss#33] opened 2017-09-08 19:07 UTC
I discovered a difference between the directory structure that was created during installation when I tried the sample layout which has widgets such as Nav referenced in the "navigation" directory in its path which doesn't exist as installed. I looked at src in a downloaded zip file and found that there are some widgets in the "navigation" and "media" directories. I simply replaced what was installed with what I found in the zip file to fix my problem. I also found that Collapsible, RangeInput, Carousel, LinkPager, MaterialBox, Parallax, and Slider had not been installed.

**Comment by MacGyer** [comment] 2017-09-08 19:29
I just did like stated in http://macgyer.github.io/yii2-materializecss/#getting-started:
```
"require": {
    "macgyer/yii2-materializecss": "*"
},
```

Composer log:
![composer](https://user-images.githubusercontent.com/2939625/30228080-7f47c9ce-94dc-11e7-8ca8-4cc0e25f7601.png)

And everything's fine:

Folder structure:
![dirs](https://user-images.githubusercontent.com/2939625/30228072-75a635ae-94dc-11e7-9ff8-472ec8833485.png)

Layout file:
![layout](https://user-images.githubusercontent.com/2939625/30228103-95b3d7ca-94dc-11e7-9db4-467b69658bb2.png)

So, please do the following:
Remove repo, and do composer update, after checking composer.json for ` "macgyer/yii2-materializecss": "~2.0"`

**Comment by wardjk** [comment] 2017-09-08 22:43
I only fixed it by using the quick workaround that I mentioned but haven't uninstalled/reinstalled to test what happened. 

I have since encountered a similar problem with the bower/materialize/dist contents which contained a "fonts" directory but scripts referencing the assets look for a "font" directory.

**Comment by MacGyer** [comment] 2017-09-16 12:27
any additional information here? If not I am closing this issue because it can't be reproduced by me.

**Comment by wardjk** [comment] 2017-09-16 14:47
No more info. I haven't installed again to try to duplicate the first installation which seemed to go smoothly (no errors or warnings) until it was put to use. I didn't try to deviate from the suggested installation instructions. It may be peculiar to my conditions (i.e. Windows 10). I wouldn't spend time on it unless someone else has similar symptoms.

**Closed** 2017-09-25 12:36 UTC
